name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Compilation du projet"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Exécution des tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Déploiement terminé"
